version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    mesh:
        image: 0xorg/mesh:7.1.1-beta-0xv3
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            ETHEREUM_CHAIN_ID: '${CHAIN_ID}'
            USE_BOOTSTRAP_LIST: 'true'
            VERBOSITY: 3
            PRIVATE_KEY_PATH: ''
            BLOCK_POLLING_INTERVAL: '2s'
            RPC_ADDR: '0.0.0.0:60557'
            ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC: '150000'
        volumes:
          - ./0x_mesh:/usr/mesh/0x_mesh
        ports:
            - '60557:60557'
    events-pipeline:
        depends_on: 
            - postgres
        image: 0xorg/event-pipeline@sha256:058e730018a8bdc31b1fdd68935eeb27bc728a0db579b41436c138cf73e830e1
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            CHAIN_ID: '${CHAIN_ID}'
            POSTGRES_URI: 'postgresql://api:api@postgres/api'
