name: Deploy
on:
    issue_comment:
        types: [created, edited]
    workflow_dispatch:
jobs:
    deploy:
        if: github.event.name == 'workflow_dispatch' || contains(github.event.comment.body, 'deploy')
        runs-on: ubuntu-latest
        steps:
            - name: deploy from master to production
              if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
              run: echo "folder=prod" >> $GITHUB_ENV
            - name: deploy from branch to staging
              if: github.event.issue.pull_request && github.event.comment.body == 'deploy staging'
              run: echo "folder=staging" >> $GITHUB_ENV
            - name: deploy from branch to production
              if: github.event.issue.pull_request && github.event.comment.body == 'deploy production'
              run: echo "folder=prod" >> $GITHUB_ENV
            - uses: xt0rted/pull-request-comment-branch@v1
              id: comment-branch
              with:
                repo_token: ${{ github.token }}
            - name: trim branch name
              run: echo ${{ steps.comment-branch.outputs.head_ref }} | sed 's/refs\/heads\///g' | xargs echo "trimmed_branch_name=$1" | sed 's/[[:space:]]//g' >> $GITHUB_ENV
            - name: Checkout 0x-main-infra
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PAT }}
                  repository: 0xProject/0x-main-infra
            - name: Update API configs
              run: sed -i -e 's/"883408475785\.dkr\.ecr\.us-east-1\.amazonaws\.com\/0x\/api\:.*"/"883408475785\.dkr\.ecr\.us-east-1\.amazonaws\.com\/0x\/api\:${{ github.sha }}"/g' env/0x-api/${{ env.folder }}/common/*.yml env/0x-api/${{ env.folder }}/apis/*.yml
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3.5.0
              with:
                  token: ${{ secrets.PAT }}
                  author: ${{ github.event.sender.login }} <${{ github.event.sender.login }}@users.noreply.github.com>
                  commit-message: '0x-api/${{ env.folder }}: Deploy ${{ env.trimmed_branch_name }}'
                  title: '[0xApi][${{ env.folder }}] Deploy ${{ env.trimmed_branch_name }}'
                  branch: '0xApi/${{ env.folder }}/${{ env.trimmed_branch_name }}'
                  body: |
                      ## Automated deploy action
                      Triggered by @${{ github.event.sender.login }}
                      PR: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})
                      SHA: https://github.com/${{ github.repository }}/tree/${{ github.sha }}
                      Comparison: https://github.com/${{ github.repository }}/compare/master...${{ steps.comment-branch.outputs.head_ref }}
            - name: Check outputs
              run: |
                  echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
